### ISSUE TITLE
Usage message is misleading

### ISSUE THREAD

**Issue by brejoc** [mgumz/csgp#3]
```
$> csgp
error: missing argument -domain
```

With this message I'd assume that I'd have to pass the domain like this: `csgp -domain example.com`
I think it would be better to make the usage message more clear.

**Comment by mgumz** [comment]
you mean like .. without the `-domain` parameter the usage itself should be given?

**Comment by brejoc** [comment]
Sorry, I was in hurry when filing the issue. Yes, I think it would be better to just print out the usage message, when `csgp` is started without any parameter. Something like this:

```
$> csgp
usage: csgp -domain="example.com"
```
